config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'maps#show'
  get 'maps/google' => 'map#google', as: :google_map

  get 'sign_in' => 'sessions#new', as: :sign_in
post 'sign_in' => 'sessions#create'
delete 'sign_in' => 'sessions#delete'

get 'registration' => 'users#new', as: :new_user
post 'registration' => 'users#create', as: :create_user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :user
    belongs_to :vacation
  
    attachment :photo, content_type: ['image/jpeg', 'image/png', 'image/gif']
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, presence: true
    has_secure_password
    has_many :vacations
    has_many :photos, through: :vacations
end

app/models/vacation.rb
class Vacation < ApplicationRecord
    belongs_to :user
    has_many :photos
    validates :name
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
    before_action except: [:new, :create] do
        if session[:user_id].nil?
            redirect_to sign_in_path, notice: 'You must sign in!'
        end
    end

    def new
        @user = User.new
        @photos = Photo.all
    end

    def create
        @user = User.new
        @user.email = params[:user][:email]
        @user.password = params[:user][:password]
        @user.password_confirmation = params[:user][:password_confirmation]
        if @user.save
            session[:user_id] = @user.id
            redirect_to user_path(id: @user.id)
        else
            render :new
        end
    end

    def show
        @vacation = Vacation.new
        @vacations = Vacation.where('user_id = ?', @current_user.id.to_s)
        @photos = Photo.where('user_id = ?', @current_user.id.to_s)
    end
end

app/controllers/api/vacations_controller.rb
class Api::VacationsController < ApplicationController
  def new
    @vacation = Vacation.new
  end

  def show
    @user = User.find_by id: params[:id]
    @photo = Photo.find_by vacation_id: params[:id]
  end

  def create
    @vacation = Vacation.new
    @vacation.user_id = @current_user.id
    @vacation.name = params[:vacation][:name]
    if @vacation.save
      redirect_to new_vacation_photos_path(vacation_id: @vacation.id)
    else
      render :new
    end
  end


  def delete
    @vacation = Vacation.find_by id: params[:id]
    Vacation.find(params[:id]).delete
    (redirect_to delete_photo_path(vacation_id: @vacation.id), method: :delete)

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_action do
        @current_user = User.find_by id: session[:user_id]
    end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action do
      redirect_to sign_in_path, notice: 'Please Sign in' if @current_user.nil?
  end


  def show
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def loc_iq
    response = Http.get("http://locationiq.org/v1/search.php?key=d1e024fcce6322e1a702&format=json&q=#{@photo.location}")
  end


    def new
        @photo = Photo.new
    end

    def create
        @photo = Photo.new
        @photo.vacation_id = params[:vacation_id]

        @photo.location = params[:photo][:location]
        @photo.user_id = @current_user.id

        response = loc_iq
        results = JSON.parse(response.body)

        @photo.latitude = results.first['lat']
        @photo.longitude = results.first['lon']

        @photo.photo = params[:photo][:photo]

        if @photo.save
            redirect_to user_path(id: @current_user.id)
        else
            render :new
        end
    end

    def edit
        @vacation = Vacation.find_by id: params[:id]
        @photo = Photo.find_by vacation_id: params[:vacation_id]
    end

    def update
        @photo = Photo.find_by vacation_id: params[:vacation_id]
        @photo.location = params[:photo][:location]
        @photo.user_id = @current_user.id

        response = loc_iq
        results = JSON.parse(response.body)

        @photo.latitude = results.first['lat']
        @photo.longitude = results.first['lon']
        @photo.photo = params[:photo][:photo]
        if @photo.save
            redirect_to user_path(id: @current_user.id)
        else
            render :edit
      end
    end

    def delete
        Photo.find_by vacation_id: params[:vacation_id].delete
        redirect_to user_path(id: @current_user.id)
      end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
end

def create

  user = User.find_by email: params[:email]
  if user && user.authenticate(params[:password])
    # make session[:username] present
    session[:user_id] = user.id
    redirect_to root_path, notice: "Signed in!"
  else
    flash.now[:notice] = "Something is wrong with your username and/or password"
    render :new
  end
end

def delete
  # we should sign out
  # make future tests if we are signed in fail
  session.delete :user_id
  redirect_to root_path, notice: "Signed Out!"
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new
        @user.email = params[:user][:email]
        @user.password = params[:user][:password]
        @user.password_confirmation = params[:user][:password_confirmation]
        if @user.save
            # we should also sign them in
            session[:user_id] = @user.id
            redirect_to root_path, notice: 'Welcome!'
        else
            render :new
        end
    end
end

app/controllers/vacations_controller.rb
class VacationsController < ApplicationController
  class VacationsController < ApplicationController
   def new
     @vacation = Vacation.new
   end

   def show
     @user = User.find_by id: params[:id]
     @photo = Photo.find_by vacation_id: params[:id]
   end

   def create
     @vacation = Vacation.new
     @vacation.user_id = @current_user.id
     @vacation.name = params[:vacation][:name]
     if @vacation.save
       redirect_to new_vacation_photos_path(vacation_id: @vacation.id)
     else
       render :new
     end
   end

   def edit
   end
 
   def update
   end

 end
end

app/helpers/api/users_helper.rb
module Api::UsersHelper
end

app/helpers/api/vacations_helper.rb
module Api::VacationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vacations_helper.rb
module VacationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vacation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>



</head>
<body>

  <div id="fb-root"></div>


  <% if @current_user %>
    <%= link_to "Sign out", sign_in_path, method: :delete %>
    <% else %>
  <%= link_to "Sign up", new_user_path %>
  <%= link_to "Sign in", sign_in_path %>

<% end %>



<%= yield %>

</body>
</html>

app/views/maps/show.html.erb
<!DOCTYPE html>
<html>
  <head>

  </head>
  <body>
    <h3>My Google Maps Demo</h3>
    <div id="map"></div>
    <script>
      function initMap() {
        var mapDiv = document.getElementById('map');
        var map = new google.maps.Map(mapDiv, {
            center: {lat: 44.540, lng: -78.546},
            zoom: 8
        });
      }
    </script>
    <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAjWDRMKvLrDwFxqutyccPKkJnn1PRg37g&callback=initMap">
    </script>
  </body>
</html>

app/views/users/new.html.erb
<h1>Hi! Sign Up!</h1>


<% if @user.errors.any? %>
<div class="alert alert-danger" role="alert">
  <% @user.errors.full_messages.each do |msg| %>
    <%= msg %><br>
  <% end %>
</div>
<% end %>

<div class="well">


<%= form_for @user, url: create_user_path do |f| %>
<div class="form-group">
  <%= f.label :email %>
  <%= f.text_field :email, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
</div>

<div class="form-group">
  <%= f.submit class: "btn btn-lg btn-primary" %>
</div>

<% end %>


</div>